### PR TITLE
Feat crud artist tattoos

### LINKED ISSUE #30: artist adds new tattoo
As a logged-in artist
When I visit my dashboard `/artists/:artist_id/dashboard`
Then I click on the "Add New Tattoo" link
Then I am taken to form that allows me to
- [ ] upload a tattoo's image
- [ ] input a time estimate
- [ ] input a cost estimate

When I fill out the form and click "Add Tattoo"
Then I am redirected to my dashboard `/artists/:artist_id/dashboard`
And I see the tattoo I just added displayed

### PR DESCRIPTION
**Pull request by laurarvegav**
## Type of change
- [x] New feature
- [ ] Bug Fix
- [ ] Refactor
- [ ] Styling
- [ ] Documentation
- [ ] Other:

## Description
This branch works on create and update actions for artist tattoos, unfinished update and delete. Still working on the testing for the edit view.

## Issue(s):
closes #30 Artist adds new tattoo
starts #20 Artist edits a tattoo info

## Necessary checkmarks:
- [ ] All Tests are Passing
- [x] The code will run locally
- [ ] Unnecessary comments removed
- [ ] Test coverage 100%

*What tests are still needed if coverage not 100%*

## Any Outstanding Issues/Problems?
- [ ] My code is wonderful, no issues here!
- [x] Yeah, see additional words below
Edit/update tests for artist tattoo still in progress. I'm having issues stubbing the returns from the API after sending any tattoo update.

### CODE REVIEW

**Review by kohljd — CHANGES_REQUESTED** [review]
Great job setting up the AWS and active storage. The tests seem setup well. I didn't merge it because I wanted a second opinion to verify about the validations.

**Comment by laurarvegav** [comment]
I just completed the edit actions, and solved the raising merge conflicts, will push again when delete action is completed for artist tattoos

**Comment by JackCSweeney** [comment]
Looks great on my end! And just confirming that yes, the validations live on the backend so no need for them here.

**Comment by laurarvegav** [comment]
Finally!!!
All tests passing :)

**Review by kohljd — APPROVED** [review]
Looks good! Thank you for making those changes

**Pull request merged**
