### PR TITLE
Feat artist sign in

### PR DESCRIPTION
**Pull request by laurarvegav**
## Type of change
- [x] New feature
- [ ] Bug Fix
- [ ] Refactor
- [ ] Styling
- [ ] Documentation
- [ ] Other:

## Description
The current:
- Creates the sessions controller with corresponding create action and log in logic  methods
- Creates the Artist poro with its attributes and initialize methods, all model tests passing.
- Creates ServiceFacade that formats /artists endpoint response and returns a collection of Artist objects, all model tests passing.
- Creates SearchService that connects to API and access /artists endpoint, all tests passing.

## Necessary checkmarks:
- [X] All Tests are Passing
- [ ] The code will run locally
- [ ] Unnecessary comments removed
- [ ] Test coverage 98.73%

*What tests are still needed if coverage not 100%*
I believe it is being picky about some specific lines but whole features are being tested

## Any Outstanding Issues/Problems?
- [X] My code is wonderful, no issues here!
- [ ] Yeah, see additional words below

### CODE REVIEW

**Comment by laurarvegav** [comment]
I wanted to push this for you to access to service and facade! I'll now start working on the artist sign in 👍

**Review by kohljd — CHANGES_REQUESTED** [review]
It looks like we missed the feature testing for where the user would actually go to the welcome page, enter their info, and sign in as an artist. The remaining test code looks good. 

For the specs, could we make a poros, features, services, and facades folders to separate the tests out into rather than models? We won't have any models at the moment since we're getting artist data through the external APIs

**Comment by laurarvegav** [comment]
Sure!!
I'll push again with the requested changes in regards of the folders :)
Will work in the actual test for signing in in happy and sad paths after that

**Comment by laurarvegav** [comment]
We only have to implement the call to verify artist sign in, is the first version of that method in the Search Service class

**Comment by kohljd** [comment]
Feature not fully complete but still merged after team discussion. New branch will be made to continue working on sign in

**Pull request merged**
